// <auto-generated />
using System;
using EDAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDAI.Data.Migrations
{
    [DbContext(typeof(EdaiDbContext))]
    [Migration("20260508000001_NullableSessionHistoryId")]
    partial class NullableSessionHistoryId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("EDAI.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EDAI.Data.Entities.EventConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<List<string>>("AnnounceFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnnounceKeys")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<List<string>>("DisplayFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DisplayKeys")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedResultsSchema")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<List<string>>("SecondaryEvents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondaryWaitTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTrayNotification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TitleDisplayMode")
                        .HasColumnType("INTEGER");

                    b.Property<List<string>>("TriggeringEvents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("EventConfigurations");
                });

            modelBuilder.Entity("EDAI.Data.Entities.ResponseLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnouncedOutput")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayedOutput")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptSent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryEventsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeringEventJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventConfigurationId");

                    b.HasIndex("SessionHistoryId");

                    b.ToTable("ResponseLogs");
                });

            modelBuilder.Entity("EDAI.Data.Entities.SessionHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommanderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JournalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionHistories");
                });

            modelBuilder.Entity("EDAI.Data.Entities.SettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysOnTop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenAiApiKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenAiModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrayNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TtsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TtsVoiceName")
                        .HasColumnType("TEXT");

                    b.Property<double>("WindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindowLeft")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindowTop")
                        .HasColumnType("REAL");

                    b.Property<double>("WindowWidth")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EDAI.Data.Entities.EventConfigurationEntity", b =>
                {
                    b.HasOne("EDAI.Data.Entities.CategoryEntity", "Category")
                        .WithMany("EventConfigurations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EDAI.Data.Entities.ResponseLogEntity", b =>
                {
                    b.HasOne("EDAI.Data.Entities.EventConfigurationEntity", "EventConfiguration")
                        .WithMany()
                        .HasForeignKey("EventConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EDAI.Data.Entities.SessionHistoryEntity", "SessionHistory")
                        .WithMany("ResponseLogs")
                        .HasForeignKey("SessionHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventConfiguration");

                    b.Navigation("SessionHistory");
                });

            modelBuilder.Entity("EDAI.Data.Entities.CategoryEntity", b =>
                {
                    b.Navigation("EventConfigurations");
                });

            modelBuilder.Entity("EDAI.Data.Entities.SessionHistoryEntity", b =>
                {
                    b.Navigation("ResponseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
